export default {
  api: {
    userAccountRequired: '請輸入用戶名',
    userAccountTooShort: '使用者帳號太短',
    userAccountTooLong: '使用者帳號太長',
    userAccountDuplicate: '使用者帳號重複',
    userAccountInvalid: '使用者帳號格式錯誤',
    userEmailRequired: '電子郵件必填',
    userEmailInvalid: '電子郵件格式錯誤',
    userPasswordRequired: '密碼必填',
    userPasswordTooLong: '密碼太長',
    userPasswordTooShort: '密碼太短',
    userPasswordInvalid: '密碼錯誤',
    userNameRequired: '姓名必填',
    userNotFound: '查無使用者',
    userPermissionDenied: '使用者權限不足',
    userNotInGroup: '使用者不在揪團中',
    userGenderInvalid: '性別格式錯誤',
    chatMessageRequired: '請輸入訊息',
    chatAlreadyExists: '聊天室已存在',
    formNickNameRequired: '請輸入暱稱',
    formEmailRequired: '請輸入電子郵件',
    formEmailInvalid: '電子郵件格式錯誤',
    formTitleRequired: '請輸入標題',
    formDescriptionRequired: '請輸入內容',
    requestFormatError: '請求格式錯誤',
    serverError: '伺服器錯誤',
    invalidInput: '輸入錯誤',
    groupNotFound: '查無揪團',
    notOrganizer: '非揪團主辦人',
  },
  group: {
    organizerIdRequired: '主辦者ID必填',
    idRequired: '揪團ID必填',
    nameRequired: '揪團名稱必填',
    nameMinLength: '揪團名稱太短',
    imageRequired: '揪團圖片必填',
    descriptionRequired: '揪團描述必填',
    descriptionMinLength: '揪團描述太短',
    contentRequired: '揪團詳情必填',
    contentMinLength: '揪團詳情太短',
    typeRequired: '揪團類型必填',
    memberCountMin: '成員數量不得少於 1 人',
    maxMembersRequired: '請設定成員上限',
    maxMembersMin: '成員上限不得少於 2 人',
    groupFull: '揪團已達人數上限',
    memberLimitRequired: '人數上限必填',
    memberLimitMin: '人數上限不得少於 2 人',
    contactMethodRequired: '聯絡方式必填',
    contactInfoRequired: '聯絡資訊必填',
    contactInfominLength: '聯絡資訊太短',
    regionRequired: '選擇地區必填',
    addressRequired: '輸入地址必填',
    tagsRequired: '標籤必填',
    tagsMinItems: '標籤太少',
    timeRequired: '揪團時間必填',
    uploadFailed: '上傳失敗',
    idInvalid: '揪團 ID 格式錯誤',
    notFound: '查無資料',
    alreadyJoined: '已加入揪團',
    alreadyOrganized: '已經是揪團主辦人',
  },
}
